import codeql.Locations
import codeql.files.FileSystem
import codeql.hcl.ast.AstNodes
import codeql.hcl.Resources
import codeql.hcl.Constants
import codeql.hcl.Locals
import codeql.hcl.Terraform
// providers
import codeql.hcl.providers.AWS
import codeql.hcl.providers.Azure
import codeql.hcl.providers.GCP
import codeql.hcl.providers.Helm
// security
import codeql.hcl.security.HardcodedPasswords
