name: "Dependency Review"
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: advanced-security/reusable-workflows/.github/workflows/dependency-review.yml@main
    secrets: inherit
