# GitHub Releasing Workflow
name: GitHub - Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "The type of version bump to perform"
        options: 
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release-next:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7.0.1

      - name: "Patch Release Me"
        # TODO: Return to the upstream action after its runtime image is digest-pinned:
        # https://github.com/42ByteLabs/patch-release-me/issues/169
        uses: docker://ghcr.io/42bytelabs/patch-release-me:0.6.7@sha256:b9624359ce08707dfb4d22bcbf9d1a75f7f4718ccec610ddaa62280ffea98958
        with:
          args: bump -m ${{ github.event.inputs.bump }}

      - name: "Bundle"
        run: |
          set -e
          cd .github/action
          npm i && npm run bundle

      - name: "Get Version"
        id: get_version
        run: |
          set -e
          pip install -r requirements.txt --require-hashes
          echo "version=$(cat .release.yml | yq -r ".version")" >> "$GITHUB_ENV"
          echo "release=true" >> "$GITHUB_ENV"

      - name: "Create Release"
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          token: ${{ github.token }}
          commit-message: "[chore]: Create release for ${{ steps.get_version.outcome.version }}"
          title: "[chore]: Create release for ${{ steps.get_version.outcome.version }}"
          branch: chore-release-${{ steps.get_version.outcome.version }}
          labels: version
          body: |
            This is an automated PR to create a new release. The release will be created once this PR is merged.
